### ISSUE TITLE
Run / compile? / test? embedded code in an emulator

### ISSUE THREAD

**Issue by mattwynne** [blaine/couloir#2]
It would be nice to be able to do some dev cycles on the embedded code without having to upload to the hardware each time, or even having the hardware present.

There is this? https://github.com/mluis/qemu-esp32/tree/main

**Comment by blaine** [comment]
Yup, that's the emulator, at least in theory! The instructions I've found describe how to run it from the esp-idf extension in vscode, nothing clear on how to do it manually

**Comment by mattwynne** [comment]
Some more stuff I found:

https://marketplace.visualstudio.com/items?itemName=espressif.esp-idf-extension
https://medium.com/@ninjapiraatti/rust-on-esp32-part-1-simulate-esp32c3-in-vscode-2df81604f1e3
https://docs.wokwi.com/vscode/getting-started

**Comment by mattwynne** [comment]
Fuck emulators. We had a good go with wokwi but it was a pain in the arse.
